// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvE7FKKI5ikXxRE3Wd9PB8dva79YkeILs',
    appId: '1:516913655806:web:826ef8e651b2748341daaf',
    messagingSenderId: '516913655806',
    projectId: 'ev-fleet-advaith-2026',
    authDomain: 'ev-fleet-advaith-2026.firebaseapp.com',
    storageBucket: 'ev-fleet-advaith-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASwylf4Dofm8jJuqxYTQ856Xu0cCOKEiQ',
    appId: '1:516913655806:android:f4083da7572ba5c041daaf',
    messagingSenderId: '516913655806',
    projectId: 'ev-fleet-advaith-2026',
    storageBucket: 'ev-fleet-advaith-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKoydWjHDB06OzbUOfZNIwOphtNuy8ZE',
    appId: '1:516913655806:ios:f5fa212738b2514441daaf',
    messagingSenderId: '516913655806',
    projectId: 'ev-fleet-advaith-2026',
    storageBucket: 'ev-fleet-advaith-2026.firebasestorage.app',
    iosBundleId: 'com.advaith.evfleet.evFleetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbKoydWjHDB06OzbUOfZNIwOphtNuy8ZE',
    appId: '1:516913655806:ios:f5fa212738b2514441daaf',
    messagingSenderId: '516913655806',
    projectId: 'ev-fleet-advaith-2026',
    storageBucket: 'ev-fleet-advaith-2026.firebasestorage.app',
    iosBundleId: 'com.advaith.evfleet.evFleetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvE7FKKI5ikXxRE3Wd9PB8dva79YkeILs',
    appId: '1:516913655806:web:f2aaea27a9cadfdf41daaf',
    messagingSenderId: '516913655806',
    projectId: 'ev-fleet-advaith-2026',
    authDomain: 'ev-fleet-advaith-2026.firebaseapp.com',
    storageBucket: 'ev-fleet-advaith-2026.firebasestorage.app',
  );
}
